/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualClassesRouteImport } from './routes/virtual-classes'
import { Route as VarkQuizRouteImport } from './routes/vark-quiz'
import { Route as UserSummaryRouteImport } from './routes/user-summary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesCourseIdRouteImport } from './routes/quizzes.$courseId'
import { Route as CoursesBuilderRouteImport } from './routes/courses.builder'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as QuizzesQuizIdTakeRouteImport } from './routes/quizzes.$quizId.take'
import { Route as QuizzesQuizIdEditRouteImport } from './routes/quizzes.$quizId.edit'

const VirtualClassesRoute = VirtualClassesRouteImport.update({
  id: '/virtual-classes',
  path: '/virtual-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const VarkQuizRoute = VarkQuizRouteImport.update({
  id: '/vark-quiz',
  path: '/vark-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSummaryRoute = UserSummaryRouteImport.update({
  id: '/user-summary',
  path: '/user-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesCourseIdRoute = QuizzesCourseIdRouteImport.update({
  id: '/quizzes/$courseId',
  path: '/quizzes/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesBuilderRoute = CoursesBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const QuizzesQuizIdTakeRoute = QuizzesQuizIdTakeRouteImport.update({
  id: '/quizzes/$quizId/take',
  path: '/quizzes/$quizId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdEditRoute = QuizzesQuizIdEditRouteImport.update({
  id: '/quizzes/$quizId/edit',
  path: '/quizzes/$quizId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/assessments': typeof AssessmentsRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/settings': typeof SettingsRoute
  '/user-summary': typeof UserSummaryRoute
  '/vark-quiz': typeof VarkQuizRoute
  '/virtual-classes': typeof VirtualClassesRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/builder': typeof CoursesBuilderRoute
  '/quizzes/$courseId': typeof QuizzesCourseIdRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/quizzes/$quizId/take': typeof QuizzesQuizIdTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/assessments': typeof AssessmentsRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/settings': typeof SettingsRoute
  '/user-summary': typeof UserSummaryRoute
  '/vark-quiz': typeof VarkQuizRoute
  '/virtual-classes': typeof VirtualClassesRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/builder': typeof CoursesBuilderRoute
  '/quizzes/$courseId': typeof QuizzesCourseIdRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/quizzes/$quizId/take': typeof QuizzesQuizIdTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/assessments': typeof AssessmentsRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/settings': typeof SettingsRoute
  '/user-summary': typeof UserSummaryRoute
  '/vark-quiz': typeof VarkQuizRoute
  '/virtual-classes': typeof VirtualClassesRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/builder': typeof CoursesBuilderRoute
  '/quizzes/$courseId': typeof QuizzesCourseIdRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/quizzes/$quizId/take': typeof QuizzesQuizIdTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/assessments'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/my-courses'
    | '/settings'
    | '/user-summary'
    | '/vark-quiz'
    | '/virtual-classes'
    | '/courses/$courseId'
    | '/courses/builder'
    | '/quizzes/$courseId'
    | '/quizzes/$quizId/edit'
    | '/quizzes/$quizId/take'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/assessments'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/my-courses'
    | '/settings'
    | '/user-summary'
    | '/vark-quiz'
    | '/virtual-classes'
    | '/courses/$courseId'
    | '/courses/builder'
    | '/quizzes/$courseId'
    | '/quizzes/$quizId/edit'
    | '/quizzes/$quizId/take'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/assessments'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/my-courses'
    | '/settings'
    | '/user-summary'
    | '/vark-quiz'
    | '/virtual-classes'
    | '/courses/$courseId'
    | '/courses/builder'
    | '/quizzes/$courseId'
    | '/quizzes/$quizId/edit'
    | '/quizzes/$quizId/take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AssessmentsRoute: typeof AssessmentsRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyCoursesRoute: typeof MyCoursesRoute
  SettingsRoute: typeof SettingsRoute
  UserSummaryRoute: typeof UserSummaryRoute
  VarkQuizRoute: typeof VarkQuizRoute
  VirtualClassesRoute: typeof VirtualClassesRoute
  QuizzesCourseIdRoute: typeof QuizzesCourseIdRoute
  QuizzesQuizIdEditRoute: typeof QuizzesQuizIdEditRoute
  QuizzesQuizIdTakeRoute: typeof QuizzesQuizIdTakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-classes': {
      id: '/virtual-classes'
      path: '/virtual-classes'
      fullPath: '/virtual-classes'
      preLoaderRoute: typeof VirtualClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vark-quiz': {
      id: '/vark-quiz'
      path: '/vark-quiz'
      fullPath: '/vark-quiz'
      preLoaderRoute: typeof VarkQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-summary': {
      id: '/user-summary'
      path: '/user-summary'
      fullPath: '/user-summary'
      preLoaderRoute: typeof UserSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$courseId': {
      id: '/quizzes/$courseId'
      path: '/quizzes/$courseId'
      fullPath: '/quizzes/$courseId'
      preLoaderRoute: typeof QuizzesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/builder': {
      id: '/courses/builder'
      path: '/builder'
      fullPath: '/courses/builder'
      preLoaderRoute: typeof CoursesBuilderRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/quizzes/$quizId/take': {
      id: '/quizzes/$quizId/take'
      path: '/quizzes/$quizId/take'
      fullPath: '/quizzes/$quizId/take'
      preLoaderRoute: typeof QuizzesQuizIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId/edit': {
      id: '/quizzes/$quizId/edit'
      path: '/quizzes/$quizId/edit'
      fullPath: '/quizzes/$quizId/edit'
      preLoaderRoute: typeof QuizzesQuizIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesBuilderRoute: typeof CoursesBuilderRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesBuilderRoute: CoursesBuilderRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AssessmentsRoute: AssessmentsRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyCoursesRoute: MyCoursesRoute,
  SettingsRoute: SettingsRoute,
  UserSummaryRoute: UserSummaryRoute,
  VarkQuizRoute: VarkQuizRoute,
  VirtualClassesRoute: VirtualClassesRoute,
  QuizzesCourseIdRoute: QuizzesCourseIdRoute,
  QuizzesQuizIdEditRoute: QuizzesQuizIdEditRoute,
  QuizzesQuizIdTakeRoute: QuizzesQuizIdTakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
