/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserSummaryRouteImport } from './routes/user-summary'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesCourseIdRouteImport } from './routes/quizzes.$courseId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as QuizzesQuizIdTakeRouteImport } from './routes/quizzes.$quizId.take'
import { Route as QuizzesQuizIdEditRouteImport } from './routes/quizzes.$quizId.edit'

const UserSummaryRoute = UserSummaryRouteImport.update({
  id: '/user-summary',
  path: '/user-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesCourseIdRoute = QuizzesCourseIdRouteImport.update({
  id: '/quizzes/$courseId',
  path: '/quizzes/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const QuizzesQuizIdTakeRoute = QuizzesQuizIdTakeRouteImport.update({
  id: '/quizzes/$quizId/take',
  path: '/quizzes/$quizId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdEditRoute = QuizzesQuizIdEditRouteImport.update({
  id: '/quizzes/$quizId/edit',
  path: '/quizzes/$quizId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/user-summary': typeof UserSummaryRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/quizzes/$courseId': typeof QuizzesCourseIdRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/quizzes/$quizId/take': typeof QuizzesQuizIdTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/user-summary': typeof UserSummaryRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/quizzes/$courseId': typeof QuizzesCourseIdRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/quizzes/$quizId/take': typeof QuizzesQuizIdTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-courses': typeof MyCoursesRoute
  '/user-summary': typeof UserSummaryRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/quizzes/$courseId': typeof QuizzesCourseIdRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/quizzes/$quizId/take': typeof QuizzesQuizIdTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/my-courses'
    | '/user-summary'
    | '/courses/$courseId'
    | '/quizzes/$courseId'
    | '/quizzes/$quizId/edit'
    | '/quizzes/$quizId/take'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/my-courses'
    | '/user-summary'
    | '/courses/$courseId'
    | '/quizzes/$courseId'
    | '/quizzes/$quizId/edit'
    | '/quizzes/$quizId/take'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/dashboard'
    | '/login'
    | '/my-courses'
    | '/user-summary'
    | '/courses/$courseId'
    | '/quizzes/$courseId'
    | '/quizzes/$quizId/edit'
    | '/quizzes/$quizId/take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyCoursesRoute: typeof MyCoursesRoute
  UserSummaryRoute: typeof UserSummaryRoute
  QuizzesCourseIdRoute: typeof QuizzesCourseIdRoute
  QuizzesQuizIdEditRoute: typeof QuizzesQuizIdEditRoute
  QuizzesQuizIdTakeRoute: typeof QuizzesQuizIdTakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-summary': {
      id: '/user-summary'
      path: '/user-summary'
      fullPath: '/user-summary'
      preLoaderRoute: typeof UserSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$courseId': {
      id: '/quizzes/$courseId'
      path: '/quizzes/$courseId'
      fullPath: '/quizzes/$courseId'
      preLoaderRoute: typeof QuizzesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/quizzes/$quizId/take': {
      id: '/quizzes/$quizId/take'
      path: '/quizzes/$quizId/take'
      fullPath: '/quizzes/$quizId/take'
      preLoaderRoute: typeof QuizzesQuizIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId/edit': {
      id: '/quizzes/$quizId/edit'
      path: '/quizzes/$quizId/edit'
      fullPath: '/quizzes/$quizId/edit'
      preLoaderRoute: typeof QuizzesQuizIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyCoursesRoute: MyCoursesRoute,
  UserSummaryRoute: UserSummaryRoute,
  QuizzesCourseIdRoute: QuizzesCourseIdRoute,
  QuizzesQuizIdEditRoute: QuizzesQuizIdEditRoute,
  QuizzesQuizIdTakeRoute: QuizzesQuizIdTakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
